### ISSUE TITLE
set user and pass didnt work

### ISSUE THREAD

**Issue by EdenSeven** [mooware/mooftpserv#1]
I just editored DefaultAuthHAdndler.cs
`
public bool AllowLogin(String user,String pass) 
{
       return(user=="admin" && pass=="123456")
}
`but it didt work,please tell me why.
with great regards
`

**Comment by mooware** [comment]
Tried it, works just fine. Are you sure that you built and deployed your modified library correctly?

**Comment by EdenSeven** [comment]
fix it .thanks a lot

**Comment by mooware** [comment]
I assume you meant that you fixed it, not that I should fix it. Closing the issue now.
