### ISSUE TITLE
Custom Command Not Receiving By Server

### ISSUE THREAD

**Issue by babusalavedu** [mooware/mooftpserv#10]
Hello,

I"m trying to send custom command to server like "REIN", "RMF", "RMX" these command not sending to server if I using Public IP. but these commands works if connect using Local IP.

Could you please help?

Thanks in Advance.
Babu.

**Comment by mooware** [comment]
I'm not sure what you mean exactly. None of these commands are supported by this server. The difference between public/local IP sounds like a simple networking issue. If you bind the server to localhost or 127.0.0.1, then it is only available locally.

Ah, maybe I see your problem now. Depending on how it is configured (active/passive), the FTP server might try to establish a connection back to the client for data transfer. In most network configurations these days, a client probably can't easily have open ports that would be accessible from the outside, thus these connections would fail. Try setting the server to passive mode.

**Comment by babusalavedu** [comment]
Thanks.
