### ISSUE TITLE
Can't upload file using command line ftp client in Windows

### ISSUE THREAD

**Issue by ViacheslavMezentsev** [mooware/mooftpserv#2]
Simple cmd:

Visator.exe - file to upload;
192.168.5.105 - ip address for Windows Embedded Compact 7 device;

```
@echo off

if exist %~dp0Visator.exe (

    echo Upload file to device ...

    (
        echo open 192.168.5.105
        echo anonymous
        echo binary
        echo cd /HardDisk
        echo literal pasv
        echo put Visator.exe
        echo quit
    ) > %~dp0upload

    ftp -s:%~dp0upload > nul

    del %~dp0upload /q > nul

    echo Done.
)

ftp> open 192.168.5.105
Связь с 192.168.5.105.
220 This is mooftpserv v1.3. Hey ho let's go!
Пользователь (192.168.5.105:(none)): anonymous
230 Login successful.
ftp> binary
200 Switching to BINARY mode.
ftp> cd /HardDisk
200 Alright, I'll do it...
ftp> literal pasv
227 Switched to passive mode (192,168,5,105,192,110)
ftp> put Visator.exe
500 Specified argument was out of the range of valid values. Parameter name: newAddress
150 Opening data connection.
```

I need upload a file using script and I don't know how to do that.

**Comment by mooware** [comment]
I haven't tested it yet, but if you're using the Windows FTP command-line client, then you should probably use active mode. This stackoverflow link tells me that this client does not support passive mode: http://stackoverflow.com/questions/18643542/how-to-use-passive-ftp-mode-in-windows-command-prompt

**Comment by ViacheslavMezentsev** [comment]
Ok, with curl passive mode works fine:

`curl -v --ftp-pasv -T Visator.exe ftp://192.168.5.105/HardDisk/ --user anonymous:`

but active mode not working:

`curl -v --disable-epsv --disable-eprt --ftp-port 192.168.5.105 -T Visator.exe -u anonymous: 'ftp://192.168.5.105/HardDisk/'`

If you find out a way how to do this using Windows FTP command-line client, please let us know.

**Comment by mooware** [comment]
Could this be a firewall or routing issue? In active mode, the client opens a socket to which the server will connect.

I tried using the Windows ftp client locally, with client and server on the same machine, and it worked and used the active mode correctly.

**Comment by mooware** [comment]
We'll, it's not a server issue, closing.
