### ISSUE TITLE
Binary for .NET CF

### ISSUE THREAD

**Issue by schtritoff** [mooware/mooftpserv#3]
Hi

Is is possible to provide compiled binary for .NET compact framework?

Thanks

**Comment by mooware** [comment]
I tried rebuilding it, but I have no idea whether it actually works. Give it a try and please let me know whether it worked: https://www.dropbox.com/s/cm9lhj3j5z3saia/mooftpserv_wince.zip?dl=0

**Comment by schtritoff** [comment]
Thanks for providing binary for Windows CE, it works. You could add it to releases page.
