### ISSUE TITLE
Enhancement request: FTPS (TLS/SSL) support.

### ISSUE THREAD

**Issue by PhonicUK** [mooware/mooftpserv#5]
It'd be very nice if support for FTP over SSL/TLS could be implemented. As it currently stands this library is clear-text only which makes it unsuitable for certain applications.

https://en.wikipedia.org/wiki/FTPS

**Comment by mooware** [comment]
I'd consider TLS support as out-of-scope. I made this project primarily to help with WinCE development, and as far as I can tell, .NET Compact Framework 3.5 (my original target) doesn't even have SSL/TLS sockets. It definitely shouldn't be used in any security-relevant context. If you're not restricted to Windows CE, then there should be plenty proper FTP servers available, or something less outdated, like SMB/SFTP/etc.

It also looks like it would be a lot of work for me even though I don't even need it. On the other hand, if you're willing to implement this feature, I'd most likely happily accept a pull request.

**Comment by PhonicUK** [comment]
It's a fairly trivial amount of work to implement, but I'd start breaking WinCE compatibility if I did that. I may yet end up having to fork entirely.
