### ISSUE TITLE
Question: Possibility to change FTP server root

### ISSUE THREAD

**Issue by fyr77** [mooware/mooftpserv#7]
Hi!
I might be blind, but is it possible to change the DefaultFileSystemHandler to not resolve the parent directories of the startPath? 
I don't want to change anything in your project here, it's just for a little project I'm using your server in.

Thanks in advance!

**Comment by mooware** [comment]
I've written this quite a while ago so I had to dig into the code a bit, but as far as I can tell, the "startPath" is not supposed to be a root or base path that you can't escape out of, but a "current directory".

Being able to define a root directory would be a reasonable feature, but it's not supported by the current code. I suppose it shouldn't be too difficult to add though. Maybe I'll take a shot at it when I find the time.

**Comment by fyr77** [comment]
Thanks for looking into that.
I'll try to implement it myself, if it works I'll create a pull request.
