### ISSUE TITLE
Question: Is FTP Server Support REST Command?

### ISSUE THREAD

**Issue by babusalavedu** [mooware/mooftpserv#9]
Hello,

1. Where can I set the root directory for the particular user?

2. Is it support REST Command for the upload and download?

Thanks in advance!

**Comment by mooware** [comment]
Hi!

Neither of those features is implemented. This program wasn't meant to be a fully featured FTP server, but mainly a simple FTP server for Windows CE devices.

I suppose both of these features would be pretty easy to implement if you are interested and able though.

**Comment by babusalavedu** [comment]
I tried to Implement REST Command but when file are append it's not in correct size. I'm using filezilla as FTP Client and also need your help to implement users root directory.
I tried it from my side but no luck
please help me
Thanks in advance

**Comment by mooware** [comment]
is there any reason you can't just use a more full-featured FTP server application that does support your requirements?

**Comment by babusalavedu** [comment]
This application is enough for me. Could you please advise Where can I set the root directory for the individual user?
I Implemented REST Feature that's works fine.

Please help.
Thanks in advance.

**Comment by mooware** [comment]
The FileSystemHandler interface and implementation currently do not support a root path, so you would have to extend those.
Then you'd have to set the root path when the user has logged in, probably somewhere here: https://github.com/mooware/mooftpserv/blob/a1b5d3565f155964dee715ccebcaadb11e054cff/lib/Session.cs#L581.
The default auth handler implementation also does not support users and only accepts the "anonymous" login, so you would also have to implement your own auth handler if you haven't already.

**Comment by babusalavedu** [comment]
Thanks. I will try.
